// <auto-generated />
using System;
using EventManager.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventManager.Infraestructura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707013825_AddSongs")]
    partial class AddSongs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("EventManager.Dominio.Entities.DJ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Djs");
                });

            modelBuilder.Entity("EventManager.Dominio.Entities.DJ", b =>
                {
                    b.OwnsOne("EventManager.Dominio.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("DJId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("DJId");

                            b1.ToTable("Djs");

                            b1.WithOwner()
                                .HasForeignKey("DJId");
                        });

                    b.OwnsMany("EventManager.Dominio.Events.Event", "EventList", b1 =>
                        {
                            b1.Property<Guid>("DJId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Duration")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("State")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DJId", "Id");

                            b1.ToTable("Event");

                            b1.WithOwner()
                                .HasForeignKey("DJId");

                            b1.OwnsMany("EventManager.Dominio.Entities.Contact", "Contacts", b2 =>
                                {
                                    b2.Property<Guid>("EventDJId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("EventId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("EventDJId", "EventId", "Id");

                                    b2.ToTable("Contact");

                                    b2.WithOwner()
                                        .HasForeignKey("EventDJId", "EventId");

                                    b2.OwnsOne("EventManager.Dominio.ValueObjects.Name", "Name", b3 =>
                                        {
                                            b3.Property<Guid>("ContactEventDJId")
                                                .HasColumnType("TEXT");

                                            b3.Property<Guid>("ContactEventId")
                                                .HasColumnType("TEXT");

                                            b3.Property<Guid>("ContactId")
                                                .HasColumnType("TEXT");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasColumnType("TEXT");

                                            b3.HasKey("ContactEventDJId", "ContactEventId", "ContactId");

                                            b3.ToTable("Contact");

                                            b3.WithOwner()
                                                .HasForeignKey("ContactEventDJId", "ContactEventId", "ContactId");
                                        });

                                    b2.OwnsOne("EventManager.Dominio.ValueObjects.Number", "Number", b3 =>
                                        {
                                            b3.Property<Guid>("ContactEventDJId")
                                                .HasColumnType("TEXT");

                                            b3.Property<Guid>("ContactEventId")
                                                .HasColumnType("TEXT");

                                            b3.Property<Guid>("ContactId")
                                                .HasColumnType("TEXT");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasColumnType("TEXT");

                                            b3.HasKey("ContactEventDJId", "ContactEventId", "ContactId");

                                            b3.ToTable("Contact");

                                            b3.WithOwner()
                                                .HasForeignKey("ContactEventDJId", "ContactEventId", "ContactId");
                                        });

                                    b2.Navigation("Name")
                                        .IsRequired();

                                    b2.Navigation("Number")
                                        .IsRequired();
                                });

                            b1.OwnsMany("EventManager.Dominio.Entities.Song.Song", "Songs", b2 =>
                                {
                                    b2.Property<Guid>("EventDJId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("EventId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Link")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("EventDJId", "EventId", "Id");

                                    b2.ToTable("Song");

                                    b2.WithOwner()
                                        .HasForeignKey("EventDJId", "EventId");
                                });

                            b1.OwnsOne("EventManager.Dominio.ValueObjects.Location", "Location", b2 =>
                                {
                                    b2.Property<Guid>("EventDJId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("EventId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("EventDJId", "EventId");

                                    b2.ToTable("Event");

                                    b2.WithOwner()
                                        .HasForeignKey("EventDJId", "EventId");
                                });

                            b1.Navigation("Contacts");

                            b1.Navigation("Location")
                                .IsRequired();

                            b1.Navigation("Songs");
                        });

                    b.Navigation("EventList");

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
